### ISSUE TITLE
Type parameter out of range (ICE)

### ISSUE THREAD

**Issue by kvark** [rust-dev-tools/rust-semverver#57]
Running against https://github.com/servo/euclid/commit/a54f33a620ee8728fc464c3ec3be7a4e97382f65

```
error: internal compiler error: librustc/ty/subst.rs:493: Type parameter `I/#3` (I/3) out of range when substituting (root type=Some(I)) substs=[T, U, I]

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:499:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::span_bug_fmt
  14: <rustc::ty::subst::SubstFolder<'a, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
  15: <rustc_data_structures::accumulate_vec::AccumulateVec<A> as core::iter::traits::FromIterator<<A as rustc_data_structures::array_vec::Array>::Element>>::from_iter
  16: rustc::ty::fold::TypeFoldable::fold_with
  17: rustc::ty::fold::TypeFoldable::fold_with
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
  19: rustc::ty::GenericPredicates::instantiate_into
  20: rustc::ty::GenericPredicates::instantiate
  21: semverver::semcheck::typeck::TypeComparisonContext::check_bounds_error
  22: semverver::semcheck::typeck::TypeComparisonContext::check_bounds_bidirectional
  23: rustc::ty::context::tls::with_related_context
  24: rustc::infer::InferCtxtBuilder::enter
  25: semverver::semcheck::traverse::run_analysis
  26: <rust_semverver::SemVerVerCompilerCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
  27: rustc::ty::context::tls::with_context
  28: rustc_driver::driver::compile_input::{{closure}}
  29: rustc::ty::context::tls::enter_context
  30: <std::thread::local::LocalKey<T>>::with
  31: rustc::ty::context::TyCtxt::create_and_enter
  32: rustc_driver::driver::compile_input
  33: rustc_driver::run_compiler_impl
  34: <scoped_tls::ScopedKey<T>>::set
  35: syntax::with_globals
  36: rustc_driver::run_compiler
  37: rustc_driver::monitor::{{closure}}
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  40: rustc_driver::run
  41: rust_semverver::main
  42: std::rt::lang_start::{{closure}}
  43: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  44: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  45: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  46: main
  47: __libc_start_main
  48: _start
query stack during panic:
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (565235ee7 2018-05-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib
```

**Comment by ibabushkin** [comment]
Thanks for your report! This looks like a bug already known (and not yet fixed), but I'm not sure. I'll have a look as soon as possible!

**Comment by kvark** [comment]
Thanks! This is not blocking me atm.

**Comment by ibabushkin** [comment]
After only a year, the issue is fixed. (though I have not pinpointed when the bug was fixed exactly)
